[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    bblanchon/ArduinoJson
    adafruit/Adafruit Unified Sensor
    adafruit/DHT sensor library
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32
